#!/usr/bin/env bash
#script that displays the time for 12 horus and 59 minutes.

i=0

while((i <= 12))
do
    echo "Hour: $i"
    m=1
    while((m <= 59))
    do
        echo "$m"
        ((m++))
    done

    ((i++))
done
